apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-thiz
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0021-tenant/tkrw-pr712-0075-0021-app/devfile-sample-thiz@sha256:dd259433da6f1b80e5e8fa70a699c1b4e316b112582c024828c51a54e686fa00
        name: my-nodejs
        resources: {}
status: {}
